### ISSUE TITLE
Client crashes when you paste something gigantic

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#100]
...such as our entire ClientRequestHandle class
also bug #100

**Comment by Bimde** [comment]
![image](https://cloud.githubusercontent.com/assets/10459097/12380794/553502da-bd49-11e5-978e-9dafd637261d.png)
Just worked fine for me, and the SQLDatabase class here is more than twice as large!

**Comment by Netdex** [comment]
It also looks like rocky road ice cream!

**Comment by ecnivo** [comment]
Is this still the issue?

**Comment by ecnivo** [comment]
Not an issue.
