### ISSUE TITLE
When the server retrieves a file from the file system, it loses newline characters

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#101]

**Comment by ecnivo** [comment]
Could not replicate.

**Comment by Bimde** [comment]
This happens every single time. How could you not replicate? You have to stop the server and restart it.

**Comment by ecnivo** [comment]
¯\_(ツ)_/¯ Will try again.

**Comment by ecnivo** [comment]
I didn't do the "restarting server" bit

**Comment by Bimde** [comment]
As of right now, that is the only way a file is retrieved from the file system. Maybe @Netdex could implement some way the loaded are released from the memory if too many files are loaded?

**Comment by ecnivo** [comment]
Sounds like a job for a queue!

**Comment by ecnivo** [comment]
Has this been fixed by stripping the \r characters?

**Comment by Netdex** [comment]
Was this fixed by adding \n to addTextDocument() in DataManagement?
