### ISSUE TITLE
Formatter explodes

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#102]
![image](https://cloud.githubusercontent.com/assets/10459097/12384939/607b31e6-bd85-11e5-9076-dd8c17ded432.png)

**Comment by Bimde** [comment]
Shouldn't indent for comments with brackets
![image](https://cloud.githubusercontent.com/assets/10459097/12384980/d1451cfc-bd85-11e5-90a6-466cdb78d221.png)

**Comment by ecnivo** [comment]
I haven't been able to replicate the first image; is that still a problem? I think these formatter issues aren't that important

**Comment by Bimde** [comment]
The first one happens due to the second issue, and if we are handing in the formatter, then we this definitely should be fixed. @Netdex

**Comment by Netdex** [comment]
Depends on #121
