### ISSUE TITLE
Renaming projects doesn't save it server side (temporarily)

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#107]

**Comment by Bimde** [comment]
Yes it does?

**Comment by ecnivo** [comment]
https://i.imgur.com/Earr16H.gifv

**Comment by ecnivo** [comment]
I don't think the server is processing the changes properly 
![image](https://cloud.githubusercontent.com/assets/10538710/12396587/3e212bb8-bdd6-11e5-909c-70889474ef30.png)

![image](https://cloud.githubusercontent.com/assets/10538710/12396598/5528e8be-bdd6-11e5-97c1-651b2bc44252.png)

INFO: writing message: {project_uuid=4f63fd50-7937-4e51-b4d1-9d46cbf40b57, session_id=5959d42a-1404-4e01-b90c-d98e862a9149, type=project_modify, project_modify_type=RENAME_PROJECT, new_name=**aaa**}
INFO: reading response...
INFO: response: {status=OK}
INFO: writing message: {session_id=5959d42a-1404-4e01-b90c-d98e862a9149, type=list_projects}
INFO: reading response...
INFO: response: {projects=[4f63fd50-7937-4e51-b4d1-9d46cbf40b57], status=OK}
INFO: writing message: {directory_uuid=4f63fd50-7937-4e51-b4d1-9d46cbf40b57, session_id=5959d42a-1404-4e01-b90c-d98e862a9149, type=**directory_info**}
>This "directory info" is just for the project's name

INFO: reading response...
INFO: response: {parent_directory_uuid=null, child_files=[], child_directories=[], directory_name=**aouioeuaoe**, status=OK}
