### ISSUE TITLE
I wonder how many marks Mangat takes off for bad spelling 

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#108]
![image](https://cloud.githubusercontent.com/assets/10538710/12396480/a74f1a7e-bdd5-11e5-8b64-eea03f1fcb19.png)

**Comment by Bimde** [comment]
Sabotaging my commit messages is an act of war.

**Comment by ecnivo** [comment]
So have we declared war on each other? I hope not.

**Comment by ecnivo** [comment]
I don't have the time to fight a war.
