### ISSUE TITLE
File type is not detected properly..?

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#112]
INFO: writing message: {project_uuid=31cfd7fb-33c0-4177-b07c-bf99f9c03125, file_name=**asnoehiansoeu.java**, session_id=f581c14d-3c23-42d9-a904-a07590e04b27, directory_uuid=31cfd7fb-33c0-4177-b07c-bf99f9c03125, type=new_text_file}
INFO: reading response...
INFO: response: {status=**INVALID_FILE_NAME**}

**Comment by Bimde** [comment]
This is probably due to the length of the file name being too long (>16 chars), but this shouldn't be a limitation, I'll remove it later today.
