### ISSUE TITLE
Client registration shouldn't result in automatic login

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#15]
Bug found where when a client registers, they get send to the main view, without being asked to log in. This is a problem because the server doesn't send back a session ID for registrations, resulting in the client sending null as the session ID when making subsequent requests (i.e. viewing a list of projects).

**Comment by ecnivo** [comment]
Can the server then send back a session_id for that?

**Comment by Bimde** [comment]
I was thinking about that. But looking at literally 100% of registration inplementations, they require you to sign up, then login through the regular dashboard

**Comment by ecnivo** [comment]
Tomorrow.

**Comment by ecnivo** [comment]
Fixed in https://github.com/ecnivo/Flow/commit/3e88db8565d0aeef09db9f6f9edc0c995716c18e
