### ISSUE TITLE
Client calls 'request_project' repeatedly

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#16]
This call occurs everytime a user moves there move inside the file-tree-panel of the left, resulting in duplicate calls returning the same result.

**Comment by ecnivo** [comment]
Ugh I'll get to it.

**Comment by ecnivo** [comment]
At least now we know where the bugs are!

**Comment by ecnivo** [comment]
@Netdex 
The client throws a nullpointerexception when trying to get the project using
`Communicator.communicate(fileListRequest).get("project", FlowProject.class)'

and also 
>java.io.EOFException at network.FMLNetworker.send(FMLNetworker.java:50)
>	at shared.Communicator.communicate(Communicator.java:22)
>	at shared.DocTree.createProjectNode(DocTree.java:106)
>	at shared.DocTree.refreshProjectList(DocTree.java:82)
>	at shared.DocTree$1.mouseClicked(DocTree.java:46)`

@Bimde 
>[[Ljava.lang.String;@d1cdb1]
>INFO: response: {projects=[Ljava.util.UUID;@1c5d9f1, status=OK}
>INFO: accepted connection from /127.0.0.1:54414
>INFO: Request assigned worker thread 1
>INFO: receive: {project_uuid=9904bc42-d4bf-4571-a1f1-43b04167e0fc, session_id=10
a4021d-126c-44b3-9c5d-82bc3561321e, type=request_project}
>The Best Project Ever
>WARNING: communication error: failed to load image contents

**Comment by Netdex** [comment]
@ecnivo The networker errors are due to the server errors, since when the server errors out it does not send a response and closes the socket immediately. This causes the networker to have an aneurism.

**Comment by Netdex** [comment]
IIRC, this was fixed.
