### ISSUE TITLE
New project creation

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#17]
Casting error on attempted project creation by client

**Comment by Bimde** [comment]
Probably trying to get a UUID as a string again. Will fix when done co-op.

**Comment by ecnivo** [comment]
Good job.

**Comment by Netdex** [comment]
That's actually the bug that I fixed in class today, so I can just push changes when I get home.

**Comment by Netdex** [comment]
Fixed 13176e2dfe5eb7439de8868424c96d5e45170168

**Comment by Netdex** [comment]
#20

**Comment by Netdex** [comment]
The 'projects' table contains 3 columns, ProjectID, ProjectName, and OwnerUsername. However, the insert statement in newProject() does not specify a value for ProjectID. This violates the NOT NULL attribute of the columns, therefore throwing an error.

**Comment by Netdex** [comment]
#21 is a dependency in order for this bug to be fixed.

**Comment by Netdex** [comment]
Fixed 624e6cf5b1ac162a36fc2cbb0cf438a4dccc20eb
