### ISSUE TITLE
Add password protection to personal information retrieval methods

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#2]
Potential implementation is forcing all method calls to include username and (encrypted) password of the client.

**Comment by Netdex** [comment]
The only possible way someone can call those methods is if they have access to the server machine, and when someone does have access to the server machine, all bets are off. Therefore, passing usernames and encrypted passwords to methods within the program is redundant. An attacker would be more likely to use reflection and just read the information from memory.

**Comment by Bimde** [comment]
Good point. Closed for now.
