### ISSUE TITLE
String.format has far worse performance than concatenation

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#22]
Even though all SQL statements were changed to use String.format, according to [this post](http://stackoverflow.com/a/2087703/3794552), String.format is **significantly** slower than concatenation. This makes me want to consider going back to concatenation, or even going as far as using a StringBuilder. 

Ideas / thoughts? Is String creation efficiency the least of our worries? Any better ways?

**Comment by Netdex** [comment]
We could easily write our own that goes through the string and replaces accordingly without formatting, it would be faster than String.format() and also be readable.
