### ISSUE TITLE
Make project reloading in the JTree work

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#26]

**Comment by ecnivo** [comment]
@Bimde can you make method to print out the contents of a project server side?

Creating new directories doesn't show up in the client, and I'm looking for issues here, but I want to make sure it's not a server side problem where the directory simply doesn't exist.

**Comment by Bimde** [comment]
OK. This will be implemented by 1 pm today.

**Comment by ecnivo** [comment]
Genius.

**Comment by ecnivo** [comment]
Structure changed completely and must be completely redone.
