### ISSUE TITLE
Closing account does not work

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#27]
This happens 
![image](https://cloud.githubusercontent.com/assets/10538710/12242362/a347a096-b866-11e5-9b82-0755b1ddad47.png)

**Comment by Netdex** [comment]
USER_TYPE is not full caps.

**Comment by ecnivo** [comment]
![Uploading image.png…]()

**Comment by Netdex** [comment]
Fixed in 0794d4545167f0ada5f9715e80b5fe87c476be5b

**Comment by ecnivo** [comment]
Debatable.

**Comment by Netdex** [comment]
The problem was that closeAccount() removes all the session IDs, making getting the username impossible after. This will be fixed.
