### ISSUE TITLE
Comparison of passwords in char arrays with .equals()

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#3]
.equals() is being used to compare two arrays, which will compare the reference but not the actual contents of the arrays.
Use Arrays.equals() instead.

[Link to File (SettingsTabs.java)](https://github.com/ecnivo/Flow/blob/a6fbaeef5dc758692a7c886085e925b51bc058cf/Flow-Client/src/settings/SettingsTabs.java#L111)

**Comment by ecnivo** [comment]
Fixed in https://github.com/ecnivo/Flow/commit/dd159b0e07601068dfce18ed3a8b95fcb04465be
