### ISSUE TITLE
Getting the children directories of a parent returns null

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#32]
Created user "h" password "h" with project "testproject" and created directories underneath, visible in Eclipse's file explorer, but when calling getDirectories for testproject, returns an empty ArrayList

**Comment by Netdex** [comment]
You must get the project again from the server, as the FlowDirectory object you have in your memory isn't automatically synchronized with the one on the server. getDirectories() doesn't magically ask the server for the directory, it tells you the directories at the point in time when you last got them from the server. FlowDirectories and all other data are just data structures, they store information and are in no way interactive. I suspect this to be the issue, but in the end something else might be completely tandoori and I might have just wasted time writing this.

**Comment by ecnivo** [comment]
I'm quite sure I ask for the project again from the server when I update the contents of the project.

**Comment by ecnivo** [comment]
I'm sure. See https://github.com/ecnivo/Flow/commit/d89dd30eba2c036fe26c5f4edb69b2ed32e1d477#commitcomment-15437118

**Comment by ecnivo** [comment]
Made irrelevant.
