### ISSUE TITLE
Implement a listener for changes

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#34]
Either three listeners for flow file, directories, and projects, so that flow file listeners are for the text documents or arbitrary documents, and then the project and directory listeners are for metadata (name, contributors, new file added to directory (file deletion in file listener?)) 

Or

One universal listener for each project, with some method to get the type of change in the event.

**Comment by ecnivo** [comment]
Okay okay 

Listener for:
1. project metadata changes (collaborators, name)
2. directory metadata changes (name)
3. file metadata changes (name)
4. document changes (additions, deletions).

Anything else?

**Comment by Bimde** [comment]
I believe the most efficient way would be for you to have one listener, and for us to use a communication protocol (similar to the one you use to send us requests).

**Comment by ecnivo** [comment]
How about one listener with one Event, and have an integer in the event that corresponds with the type of change:

0: New/deleted projects (changes in list of projects)
1: Changes in metadata for things in a project (if that's the case, then 0 for projects, 1 for dirs, 2 for files)
2: Changes in actual document content (additions/deletions)

?

**Comment by Bimde** [comment]
That, but shouldn't we just do it the same way you send requests to us?

**Comment by ecnivo** [comment]
So I have to have a listener for requests? Let's solve this later

**Comment by ecnivo** [comment]
@Netdex What about the other listeners (file structure metadata)?

**Comment by Netdex** [comment]
The client sees multiple listeners but they are abstracted away to only one socket.
