### ISSUE TITLE
Cast of Math.random() is always 0

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#4]
Casting of Math.random() to int is done before multiplication, so the result is always 0.

[Link to File (UserCaret.java)](https://github.com/ecnivo/Flow/blob/a6fbaeef5dc758692a7c886085e925b51bc058cf/Flow-Client/src/editing/UserCaret.java#L37)

**Comment by ecnivo** [comment]
fixed in https://github.com/ecnivo/Flow/commit/a9cdec1a084255a1414f9795fd9ecc587cf10921
