### ISSUE TITLE
Why is request_project an invalid request type?

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#41]
![image](https://cloud.githubusercontent.com/assets/10538710/12357294/1426d92e-bb75-11e5-9694-0057cb319667.png)
![image](https://cloud.githubusercontent.com/assets/10538710/12357308/2143975a-bb75-11e5-8750-ea044ab5ca0f.png)

**Comment by ecnivo** [comment]
At least change the documentation first!
![image](https://cloud.githubusercontent.com/assets/10538710/12357554/708f55fa-bb76-11e5-93b7-eb822c33cc53.png)

**Comment by ecnivo** [comment]
Dicks.

**Comment by Bimde** [comment]
This was changed for consistency amongst the other 'x_info' requests.However, is this causes any problems, we could change it back.

**Comment by ecnivo** [comment]
Nope, all my code is now "project_info"
