### ISSUE TITLE
project_info returns null

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#42]
Client says
![image](https://cloud.githubusercontent.com/assets/10538710/12357739/a0e5c788-bb77-11e5-87ef-f420ca8ca573.png)

Server says 
![image](https://cloud.githubusercontent.com/assets/10538710/12357748/af0c4eae-bb77-11e5-8a32-6ea952f8a137.png)

**Comment by Bimde** [comment]
Fixed in https://github.com/ecnivo/Flow/commit/ac3aa8546c0fa305e859e239f7af17e27c101019
