### ISSUE TITLE
Prevent duplicate names

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#48]
1. A user's projects should all have unique names
2. A directory's children directories should all have unique names
3. A directory's children files should all have unique names

So theoretically Workspace/name/name/name is allowed?

**Comment by Bimde** [comment]
yes, workspace name/name/name is allowed.

**Comment by ecnivo** [comment]
So does it return invalid name or something?

**Comment by Bimde** [comment]
Returns the specifed messages in the documentation.

**Comment by ecnivo** [comment]
Not working. 
![Uploading image.png…]()
