### ISSUE TITLE
Change of implementation for versioning

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#5]
`TreeMap`s are no longer used to store document version information. They are now stored with `TreeSet`s, with each `Document` having a `.getVersionDate()` method.

[Link to File (VersionViewer.java)](https://github.com/ecnivo/Flow/blob/a6fbaeef5dc758692a7c886085e925b51bc058cf/Flow-Client/src/history/VersionViewer.java#L76)

**Comment by ecnivo** [comment]
Implemented in https://github.com/ecnivo/Flow/commit/a9cdec1a084255a1414f9795fd9ecc587cf10921
