### ISSUE TITLE
Server is not adding a text file's lines

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#51]
How to replicate: 
1. Create new user
2. Create new project
3. Create new text file in project
4. double click on text file
5. type ONE letter into the tab.
Console should  read `[] line 0 set to "Q"` (or whatever letter you typed)
This is correct, because it will print out the ArrayList of lines BEFORE any additions (in which it will be blank), then it'll print what changes have been made.
6. Type a second letter
Console should read `[] Exception in thread "Thread-21" java.lang.ArrayIndexOutOfBoundsException: Index 1 in line 0 is out of range (max is 0)`
This is wrong, because the console should actually read ["Q"] line 0 set to "QK" since "Q" was added to the line already.

I suspect that the server is creating a new VersionText every time.
Link to file is here: https://git.io/vzClt

**Comment by Netdex** [comment]
Text documents were being loaded from disk but not saved each time. This is being fixed.

**Comment by ecnivo** [comment]
kkk
