### ISSUE TITLE
Client sends line and index numbers after change

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#59]
The client should send line and index numbers BEFORE the change happens.

**Comment by ecnivo** [comment]
That's not possible; how do you predict what the user's going to type before they type it? 

As it currently stands, the server is contacted between when Flow receives the keystroke and when the letter is actually shown in the JTextPane.

**Comment by Netdex** [comment]
no longer an issue because line numbers are gone.

**Comment by ecnivo** [comment]
That too.
