### ISSUE TITLE
Deleting a folder wipes the entire tree client side

### ISSUE THREAD

**Issue by Netdex** [ecnivo/Flow#65]

**Comment by ecnivo** [comment]
It does?

**Comment by Netdex** [comment]
Until restart

**Comment by ecnivo** [comment]
I'll try it once @Bimde un-corrupts the .db

**Comment by ecnivo** [comment]
Could not replicate. https://i.imgur.com/Zq3KqKP.gifv

**Comment by Netdex** [comment]
CRITICAL ISSUE!
http://i.imgur.com/txaIBuv.gifv

**Comment by Bimde** [comment]
Are we sure this issue is client-side only?

**Comment by Netdex** [comment]
Yep, they reappear when the client is restarted.

**Comment by Bimde** [comment]
Ok, then client-side it is.
