### ISSUE TITLE
project_modify adding collaborators adds without checking

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#72]
I can add user aoeuaoeua without the server even checking if such a person exists (they don't) and then when I try sending a request to change aoeuaoeua's permissions, server says that person doesn't exist.

**Comment by ecnivo** [comment]
Whoops, doesn't exist anymore.

**Comment by Bimde** [comment]
This was fixed in https://github.com/ecnivo/Flow/commit/29e088a834d61149fd01264b44beddf544021df2
