### ISSUE TITLE
Files don't show up on the other user's file tree

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#74]
![image](https://cloud.githubusercontent.com/assets/10538710/12374918/09d367d4-bc7a-11e5-98ad-3e9500b00cff.png)

**Comment by Bimde** [comment]
Is this a client-side or server-side issue?

**Comment by ecnivo** [comment]
I think it's server side, because I keep refreshing the second side, and it's not showing up.

**Comment by ecnivo** [comment]
It works.
