### ISSUE TITLE
Client crashes if they lose access to a project and request file

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#75]
![image](https://cloud.githubusercontent.com/assets/10459097/12375087/6073b728-bc80-11e5-985e-203fb590be2c.png)

**Comment by ecnivo** [comment]
I'm aware. Could you return a particular message on file_request (I think, correct me if I'm wrong) if it's access denied? (ref #76 )

**Comment by ecnivo** [comment]
@Bimde How do you replicate?

**Comment by Bimde** [comment]
This will be fixed in #85

**Comment by ecnivo** [comment]
I thought this was fixed with https://github.com/ecnivo/Flow/blob/master/Flow-Client/src/editing/EditorDocTree.java#L264
