### ISSUE TITLE
INVALID_SESSION_ID too generic?

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#76]
This is used if the session_id is actually invalid, or whenever a user's session_id doesn't allow them to perform the desired action (i.e. edit a project when they are a viewer). 

Should this be split to two separate messages? I.e. 'ACCESS_DENIED' and 'INVALID_SESSION_ID'?

**Comment by ecnivo** [comment]
Split.

**Comment by Bimde** [comment]
Ok, split it is.
