### ISSUE TITLE
Owner can reduce his own access level without making anyone else the owner

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#77]
Then the client explodes.

**Comment by ecnivo** [comment]
That shouldn't happen, because in the newest update of the client (I'm still working on stuff, so I don't want to push half-working code), you can't click on the owner's permissions tile

**Comment by Bimde** [comment]
Server-side security flaw fixed in https://github.com/ecnivo/Flow/commit/99c2242d8b2b53be39365db73a41f0db0b321d8e
