### ISSUE TITLE
How to generate checksum for existing file? 

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#9]

**Comment by Bimde** [comment]
You can get a file checksum using the "file_checksum" request (fairly obvious). But this feature still isn't implemented server side. @Netdex?

**Comment by ecnivo** [comment]
Sorry, to clarify. I need to get the checksums for files already downloaded, because I need to check against the server (eventually...?)

**Comment by Netdex** [comment]
Checksum.getChecksumFromFile(File file)
