### ISSUE TITLE
Saving and Retrieving documents doesn't work properly 

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#90]
I think the issue is that you're not flushing to disk frequently enough, and when the second client opens it again, you're retrieving it from disk a long time ago. Possible fix: each time someone tries to OPEN a file, either save it to the disk then retrieve it, or send them the bytes[] of the one in RAM
https://i.imgur.com/MPdjO8f.gif

**Comment by Bimde** [comment]
Fixed.
