### ISSUE TITLE
Check if file system and database are in sync

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#94]
Do this in the database integrity check in the beginning.

**Comment by ecnivo** [comment]
@Bimde Is this being done in the database integrity check in the beginning?

**Comment by Bimde** [comment]
Not implemented yet on master as it caused other issues.

**Comment by ecnivo** [comment]
Maybe branch it off onto something that makes more sense? Like 'unstable'

**Comment by Bimde** [comment]
Or maybe 'actually works'.
