### ISSUE TITLE
Importing doesn't show all folders available in disk

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#96]
Only shows .txt and .java files:
![image](https://cloud.githubusercontent.com/assets/10459097/12380481/0012f250-bd42-11e5-90b7-0168d225a66a.png)

But shows everything when selecting all files (obviously):
![image](https://cloud.githubusercontent.com/assets/10459097/12380484/12484bbe-bd42-11e5-96e7-5dbbb25945c3.png)

**Comment by ecnivo** [comment]
![image](https://cloud.githubusercontent.com/assets/10538710/12380507/89941504-bd42-11e5-8586-09eb981da896.png)
What would happen if you selected a .wmv file or something? I don't know. That's why it's limited to that for now.

**Comment by Bimde** [comment]
In a normal file selector, it restricts you to file types, but shows all available folders as well.
![image](https://cloud.githubusercontent.com/assets/10459097/12380536/22a4b76c-bd43-11e5-8608-cab6cdd9ba58.png)

**Comment by ecnivo** [comment]
See #97

**Comment by Bimde** [comment]
Two unrelated things.

**Comment by ecnivo** [comment]
Awesome :)
