### ISSUE TITLE
Failed to edit file messages still change file client-side

### ISSUE THREAD

**Issue by Bimde** [ecnivo/Flow#98]
This:
![image](https://cloud.githubusercontent.com/assets/10459097/12380542/46aa82ae-bd43-11e5-9c5e-73adeaf64a12.png)

Paste code:
![image](https://cloud.githubusercontent.com/assets/10459097/12380503/7cea7f82-bd42-11e5-8c3f-445673051e81.png)

Then this:
![image](https://cloud.githubusercontent.com/assets/10459097/12380514/b22adc6e-bd42-11e5-806c-ddd44d848a51.png)

But obviously the database didn't save these changes, hence the error message.

**Comment by ecnivo** [comment]
That's happening because I don't think the insertUpdate and removeUpdate are being "vetoed" or "stopped" accordingly.
